version: "3.9"

services:
  web:
    build: .
    container_name: cojines-web
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://admin:admin123@172.21.0.8:5432/cojines
      PORT: 5000
